### ISSUE TITLE
How to evaluate the reconstruction results

### ISSUE THREAD

**Issue by liushuishui7** [Anomymous2024/PointDreamer#1]
Thank you so much for this excellent work. I would like to ask how to evaluate the results and how to get precision indicators such as PSRN

**Comment by Anomymous2024** [comment]
Hi! Thank you for your interest.

**How to get indicators such as PSNR:** Please check ./utils/metric_utils.

**How to generate images for evaluation:** For a thorough evaluation, we render the GT and reconstructed meshes for 20 views by positioning the cameras on the vertices of a regular dodecahedron. 

**What are the view points used for rendering:** The 20 camera views can be found in utils/camera_utils.py Line 135.
**How to render result:**  we use 'render_textured_meshes_shapenet2()' from utils/camera_utils.py. 

Also, I just upload ./run_evaluation.py, which I used for the whole evaluation. Currently, it's only for reference, since only quick demo code is released and batch-wise code hasn't yet, while run_evaluation.py requires organizing the batch-wise results in a ShapeNetCoreV2-like style.  You can reference this file, and write your own code for evaluating a single sample.

I hope this helps.
